# Introduction to coding 
- By now, you've already done some coding (maybe a lot)
- In this course, we'll focus on using Jupyter and GitHub
- If you do not have a strong coding background, do not panic!
    - We start pretty fast. You'll pick it up as you go :-)
- Again - DON'T PANIC!

- yet

# In class today, we'll 
- Create a Github repo
- Create a notebook in the repo
- Edit the notebook using google colab or using a local Jupyter exe
- Submit a "commit" back to our repo
- Start working with Jupyter Notebooks.

All of this will make more sense as we progress :-)

# Github
- Github is to help with Version control
    - No more file1.r, file2.r, etc.
- Github is to help organize MEANINGFUL UPDATES
    - It is not a generic tool for backup. Please use drive, onedrive, etc. for this.
        - But, be careful using drive + Github on the same directory!!
    - It is for providing purposeful, commented, significant updates to a code-based project
    - It is really good for team-based work, though this typically still requires additional organizational tools
        - Trello
- Example: https://github.com/jshoe1984/Grad_Math

# Download example files to work with

- Download the "2 Introduction to GitHub & Jupyter.ipynb" file only.
    - Right click "save link as"
- Do not download other files. We'll make those.

# Create your repo
- Profile / Repositories
- Select new repo.
    - Give the repo a useful name
    - Keep it private for now
    - Add a read me file. We'll edit later
    - Add the .gitignore file for "python". This will include jupyter notebooks
    - Upload jupyter notebook

# Now, you're all ready to code if you want to use Colab to edit your notebook

- An annoying thing about coding: the environments and options are always changing >.<
- Please code in the environment you're comfortable with. Be it Colab or local Jupyter.

![My way is better](https://github.com/jshoe1984/Grad_Math/blob/main/images/me_way_better.gif?raw=1)


# Now, you're all ready to code if you want to use Colab to edit your notebook

- An annoying thing about coding: the environments and options are always changing >.<
- That said, I'll show some ways to integrate GitHub and Jupyter. More exist
- And as we progress, I will cover SOME packages. Not all. Use your favorite
- **But avoid being snippy about your favorite tools**
- Quick colab demo

# GitHub + Colab
- Really convenient
- But
  - Repo must be public to link & see images
  - Mostly useful for code/script editing ONLY
  - Doing more complex work, like needing to add multiple files types and content can be very tedious still

# GitHub + Continuous Backup (drive, onedrive, etc.)
- It's not recommended to use GH as a generalized backup tool.
- And using GH with backup tools can sometimes lead to conflicts if not being careful
    - I.e., google drive didn't sync, then run GH, then drive syncs, and everything's a mess
    - obviously a bigger issue when working in teams
- Recommended way:
    - Use drive/equivalent to backup continously across all machines
    - Only use GH from a designated machine.
    - Be sure/confident that all files are synced and ready for a GH update.
- There are other backup services that handles these issue, but most cost money or are in early development.

# GitHub + Jupyter Notebooks (locally)
- This is certainly the easier and more professional way to work with GitHub and coding
- First, use GitHub desktop to clone your repo to your device
- It is not recommended to clone the repo to a google drive/onedrive directory
  - Update conflicts can occur
- Once cloned, you can operate on your code and data on your device.

# To start coding with Jupyter locally
- Download the github desktop app
- After installing, clone your repo to a local directory
- "Cloning" will put a local copy on your machine
- Can now edit with Jupyter on your machine. 
- From here, for a basic GitHub user, you're ready to go
    - For more advanced uses, typically when more than 1 user, you'll have to learn "Commit - Pull - Push"
    - Commit: any edits you made to code are accepted to be integrated into the online repo
    - Pull: pull down the most recent code, so that edits others made while you worked are incorporated
    - Push: Git will check for conflicting edits. If none, you push theh new code to the repo

# Primer for Python coding with Jupyter Notebooks

Jupyter is a handy way to develop code. It allows you to integrate text, images, references and more into the code development process. This primer is a quick reference guide showing many of the basics of coding Python with Jupyter. However, there are far better references and guides you can find online:
- Jupyter Primer : https://www.dataquest.io/blog/jupyter-notebook-tutorial/
- Python and Numpy : https://www.w3schools.com/python/numpy/default.asp
- Jupyter and Python Intro by Dr. John Kitchins : http://kitchingroup.cheme.cmu.edu/f19-06623/01-jupyter.html

But ultimately the best way to learn code is by seeing code others have written! 


# How to open a notebook

1. To do locally, install anaconda. This will install notebooks automatically.
    1. Let's restart my session and show everyone how to turn on and get started
2. You can also code on Google's Colab
    1. Free and easy to set up. Do need a google account and use google drive to keep files organized.
    2. Can only run code while connected to internet.
    3. For short blurbs of code, can be a little annoying as it will take longer to run.
    4. BUT, for more advanced codes, the Colab server is fast and you can access GPUs.

# First thing to know about Jupyter is how to use Cells

This box you are reading is a "cell". And cells come in 2 basic forms: a **Code** cell and a **Markdown** Cell. To add a cell, you can use the "Insert" pulldown tab and place a new cell above or below your current location. Or you can use short cut keys, which I'll define below. 

**Code Cells**: If a cell is set to "Code", this is where you enter code that will be executed/rendered. In code cells is where most of the action will occur. New cells are usually defaulted to be code cells, but you can also set them by selecting the pull down tab (right below Widgets above) or press ESC and then C.

**Markdown Cells**: Markdown is used to markup (I know...) the document. Here is where you can provide text and images to support your code development. Mardown cells will not execute Python code included inside. You can set a sell to be a markdown cell by selecting the pull down tab (right below Widgets above) or press ESC and then M.

So with that basic knowledge, it's easier to learn Jupyter by running through some examples. Below will provide some example markdown and the provide an example Jupyter usecase. 

# Markdown (double click to see code if already executed)

Taking notes while coding used to be very limited and look something like this:

% I wrote something below...I hope it works

% I don't know what z is...hopefully it doesn't have units.

% This is version like...97ish of this code.

x <- z+sin(x);

return(x)

Well "markdown" is an easy to learn markup language for formatting plain text. You can use markdown to better take notes while coding. But first, it is helpful to know some of the basics. But *note*, this is the basics. A lot more can be done with markdown to make a document look great.


## This is a level 2 heading

### This is a level 3 heading

This is some plain text that forms a paragraph. Add emphasis via **bold** and __bold__, or *italic* and _italic_. 

Paragraphs must be separated by an empty line. 

* Sometimes we want to include lists. 
* Which can be bulleted using asterisks. 

1. Lists can also be numbered. 
2. If we want an ordered list.

[It is possible to include hyperlinks](https://shoemakerlab.pitt.edu)

**Inline code** uses single backticks: `print('Hello')`, and code blocks use triple backticks: 
```
a = 6+10
a
``` 
Or can be indented by 4 spaces: 

    foo()

But note that inline code **does NOT execute.** This is just a way to "type up" a code in a presentable manner 
    
<span style='background:yellow'> You can also add some nice colors edits by leaning on html calls  </span>

You can also add images: ![Alt text](http://shoemakerlab.pitt.edu/images/banner.jpg)

And last but certainly not least, we can paste in some great mathematics. Jupyter uses Latex and Mathex for presenting equations. Here's a useful example:

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xy
\end{align}

See https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Typesetting%20Equations.html# for more examples
 

# Now coding - AKA The FUN PART!!

If you have experience with MATLAB, C++, R, Julia or any other programming language, you'll be able to pick up Python quite quickly. If you are very new to programming or avoided it in undergad - big mistake :-) but now we have time to fill in that void.

The only way to learn is to practice and to lean on previous code. In this course, we'll be doing primarily low-complexity coding. You will be able to perform simulations and data analysis so long as you can:

- Find the necessary Python library/package
- Load data into the Python environment
- Edit the vector/matrix indexes correctly (probably the hardest part!)
- Run the different algorithms from the packages

Below, we'll run some very basic steps, first focusing on the biggest announce when learning Python: indeces. 

Run the cell below using CTRL + ENTER. And notice the following:
1. First, we import a library called numpy and then give the algorithms inside the library a handle, np, that can be used to call the algorithms. Numpy contains a lot of algorithms for handling matrices and we'll learn them as we go along. By assigning NP as the handle, you can call algorithms inside of numpy, such as the "arange" function, by first indicating the handle and then function name (e.g. np.arange().
2. Running np.arange results in x, a vector with 10 entrees that go from 2 to 10.
3. x[2] - **this is where things get interesting** - notice when we ask for the second entree of x...we get the 3rd! Python indexing starts from **ZERO**. This takes practice to get used to.


In [ ]:
import numpy as np

x = np.arange(10)+2
print(x)
print(x[2])

# note Note: The result includes the start index, but excludes the end index.
print(x[2:5])
print(x[:-8])
print(x[-2])

print(x[np.array([2,6])])

np.arange(0,100,1)

[ 2  3  4  5  6  7  8  9 10 11]
4
[4 5 6]
[2 3]
10
[4 8]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Functions

Functions are probably one of the trickiest things to learn while coding. The best way to understand how functions work is to build your own and see what they can do. Below, we have a simple function where if given some value of x and t, the function will calculate the double of x and return that value.

I wrote this function awkwardly to point out some features of functions to be aware of:
 - The code in the function doesn't use t. BUT, the function as written asks for t and y. In order to run this, a fake value for t has to be entered. This is important to understand because many differential equation functions always ask for a value of t - even when there is not t in the equation. 
 - **Nested variables**: these are variables inside a function, e.g. "a" below. Anything nested inside a function only exists inside the function. If you try to print the value of a, an error will occur because a doesn't exist.

In [ ]:
def f(x,t):
    a=10
    y = x * 2
    return y

print(f(10,4))
print(f(20,200))

# IMPORTANT TO KNOW ABOUT FUNCTIONS. This won't work
# print(a)

20
40


## Plotting

You can plot pretty much anything with matplotlib or ggplot and there is an excellent collection of examples with code here:

https://matplotlib.org/stable/gallery/index.html

https://realpython.com/ggplot-python/

https://ggplot2.tidyverse.org/

Here are some sample graphics.

<img src="https://matplotlib.org/stable/_images/sphx_glr_bar_label_demo_001.png">
<img src="https://matplotlib.org/stable/_images/sphx_glr_markevery_prop_cycle_001.png">

# Math functions and libraries

It's important to remember that Python is a pure coding language. Basic functions that you have used in other programs, e.g. MATLAB, already have several mathematical functions built in. Python **does not**. A simple example is the sin function. For functions like this and others we might come across, you will have to identify and load the correct library. To use sin functions or exponential functions, you will have to load the math library. For matrices, we'll need numpy. In general, we'll rely on the following most often:
1. Numpy - handles matrices
2. Math - basic math functions
3. Matplotlib - plotting
3. Pandas - data frames
4. SciPy - optimization, linear algebra, integration, interpolation, special functions, FFT, signal and image processing, ODE solvers